apiVersion: v1
kind: Service
metadata:
  labels:
    app: aigreen-ctxprovider
  name: aigreen-ctxprovider-svc
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: aigreen-ctxprovider