apiVersion: v1
kind: PersistentVolume
metadata:
  name: aigreen-ctxconsumer-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: aigreen-ctxconsumer-data-pvc
  hostPath:
    path: "/home/algo/volumes/digesto/backend/customization"
    type: DirectoryOrCreate