# just needed for testing external access before adding an ingress entry for the service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aigreen-dataconsole
  name: aigreen-dataconsole-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    port: 1880
    protocol: TCP
    targetPort: 1880
    nodePort: 32120
  selector:
    app: aigreen-dataconsole