apiVersion: v1
kind: Service
metadata:
  labels:
    app: aigreen-dataconsole
  name: aigreen-dataconsole-svc
spec:
  ports:
  - name: http
    port: 1880
    protocol: TCP
    targetPort: 1880
  selector:
    app: aigreen-dataconsole