apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# ctxprovider service
# ctxconsumer service
# dataconsole (nodered) service

# @TODO: add specific descriptors' yaml, below example from /aigreen 
# backend service
# - aigreen-backend-customization-pv.yaml
# - aigreen-backend-customization-pvc.yaml
# - aigreen-backend-models-pv.yaml
# - aigreen-backend-models-pvc.yaml
# - aigreen-backend-deployment.yaml
# - aigreen-backend-nodeport.yaml
# - aigreen-backend-svc.yaml
