apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# ctxprovider service
- aigreen-ctxprovider-deployment.yaml
- aigreen-ctxprovider-nodeport.yaml
- aigreen-ctxprovider-svc.yaml

# ctxconsumer service
- aigreen-ctxconsumer-data-pv.yaml
- aigreen-ctxconsumer-data-pvc.yaml
- aigreen-ctxconsumer-deployment.yaml
- aigreen-ctxconsumer-nodeport.yaml
- aigreen-ctxconsumer-svc.yaml

# dataconsole (nodered) service
- aigreen-dataconsole-data-pv.yaml
- aigreen-dataconsole-data-pvc.yaml
- aigreen-dataconsole-deployment.yaml
- aigreen-dataconsole-nodeport.yaml
- aigreen-dataconsole-svc.yaml
