# just needed for testing external access before adding an ingress entry for the service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aigreen-backend
  name: aigreen-backend-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32000
  selector:
    app: aigreen-backend