# just needed for testing external access before adding an ingress entry for the service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aigreen-backend-dbadmin
  name: aigreen-backend-dbadmin-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32080
  selector:
    app: aigreen-backend-dbadmin