apiVersion: v1
kind: Service
metadata:
  labels:
    app: aigreen-backend-db
  name: aigreen-backend-db-svc
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: aigreen-backend-db