apiVersion: v1
kind: Service
metadata:
  labels:
    app: aigreen-backend-dbadmin
  name: aigreen-backend-dbadmin-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aigreen-backend-dbadmin