apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aigreen-frontend
  name: aigreen-frontend-deployment
spec:
  selector:
    matchLabels:
      app: aigreen-frontend
  template:
    metadata:
      labels:
        app: aigreen-frontend
    spec:
      containers:
        - image: "cmelchiorre/kitt4sme:ta08-frontend-0.1.2-test-base-href-3"
          imagePullPolicy: Always
          # image: "cmelchiorre/kitt4sme:ta08-frontend-0.1.1"
          # imagePullPolicy: IfNotPresent
          name: aigreen-frontend
          ports:
          - containerPort: 4200
            name: http