apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aigreen-backend
  name: aigreen-backend-deployment
spec:
  selector:
    matchLabels:
      app: aigreen-backend
  template:
    metadata:
      labels:
        app: aigreen-backend
    spec:
      # @TODO: see ./README.txt securityContext note
      securityContext:
        fsGroup: 1001
      containers:
        - image: "cmelchiorre/kitt4sme:ta08-backend-1.0.0"
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          name: aigreen-backend
          ports:
          - containerPort: 5000
            name: http
          env:
          - name: "ORION_BASE_URL"
            value: "http://172.16.0.169/orion"
          volumeMounts:
            - mountPath: /opt/app/nn_web_service/saved_models
              name: aigreen-backend-models-pvc
            - mountPath: /opt/app/nn_web_service/config/customization
              name: aigreen-backend-customization-pvc
      volumes:
        - name: aigreen-backend-models-pvc
          persistentVolumeClaim:
            claimName: aigreen-backend-models-pvc
        - name: aigreen-backend-customization-pvc
          persistentVolumeClaim:
            claimName: aigreen-backend-customization-pvc