# just needed for testing external access before adding an ingress entry for the service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aigreen-backend-db
  name: aigreen-backend-db-nodeport
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 33306
  selector:
    app: aigreen-backend-db